name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -o output

      - name: Zip Lambda Package
        run: cd output && zip -r ../lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Ensure S3 Bucket Exists
        run: |
          aws s3api head-bucket --bucket dotnet8-lambda-bucket-unique || aws s3 mb s3://dotnet8-lambda-bucket-unique

      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://dotnet8-lambda-bucket-unique/

      - name: Move Lambda ZIP to Terraform Directory
        run: mv lambda.zip terraform/lambda.zip

      # ✅ Use Prebuilt Terraform GitHub Action
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Adjust to latest if needed

      - name: Apply Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
